apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
        <head>
            <title>Hello</title>
        </head>
        <body>
            <p>Hello world ! v1</p>
        </body>
    </html>

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
